service: goodbye-service
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-2

plugins:
  - serverless-webpack
  - serverless-offline
  # - serverless-plugin-webpack
  # - serverless-plugin-typescript

functions:
  hello:
      handler: app/index.handler
      events:
        - http:
            path: goodbye
            method: get
